
spring:
  application:
    name: zwen-Passbook
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/passbook?autoReconnect=true
    username: root
    password:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: passbook
    listener: 4
  data:
    hbase:
      quorum: 127.0.0.1:2181
      rootDir: file:///usr/local/var/hbase
      nodeParent: /hbase
  redis:
    host: 127.0.0.1
    port: 6379


server:
  port: 9528

logging:
  file: zwen-passbook.log
  level: debug
